image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 5432
    visibility: private
    onOpen: ignore

tasks:
  - name: phoenix
    init: >
      asdf install &&
      asdf global erlang 27.0.1 &&
      asdf global elixir 1.17.2-otp-27 &&
      asdf global nodejs 14.17.6 &&
      mix local.rebar --force &&
      mix local.hex --force &&
      mix deps.get &&
      mix compile &&
      MIX_ENV=test mix compile &&
      npm install --save --prefix assets &&
      echo "Init tasks complete!"
    command: >
      cd $GITPOD_REPO_ROOT &&
      npm install -g spaces-cli &&
      mix local.rebar --force &&
      mix local.hex --force &&
      mix ecto.create &&
      mix ecto.migrate &&
      iex -S mix phx.server

vscode:
  extensions:
    - elixir-lsp.elixir-ls
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - bradlc.vscode-tailwindcss
    - https://github.com/qcitizen/vscode-extensions/raw/develop/phoenixframework.phoenix-0.1.1.vsix